-- =============================================================================
-- Migration:  V20260507100__audit_logs.sql
-- Module:     platform
-- Date:       2026-05-07
-- Author:     CogniLogistic Platform Team
--
-- WHAT THIS MIGRATION DOES:
--   Creates the cross-cutting `audit_logs` table — the append-only record of every
--   tracked mutation across the platform (orders, tenders, offices, tp_accounts,
--   users, companies, partner_tp_profiles, etc.).
--
-- WHY THE TABLE EXISTS:
--   1. Compliance — DPDP requires a 7-year audit trail for any change to user-facing data.
--   2. Support / forensics — answers "who changed this and when?" for any tracked entity.
--   3. Admin impersonation accountability — `impersonated_by_user_id` lets ops query
--      "what did Admin X do across the platform during impersonation sessions?"
--      (See platform.md §4 + admin.md §3.6.)
--
-- DESIGN DECISIONS:
--   - PK is CHAR(36) UUID (server-generated by AuditService). Uniform with the rest of
--     v5.0 schema, avoids ID collisions across modules.
--   - NO foreign-key constraints. Referenced rows (users, orders, etc.) may legitimately
--     be deleted in the application's lifetime, but the audit row must survive. We pay
--     the small cost of orphan-string IDs in exchange for a true append-only table.
--   - actor_name is denormalised — snapshots the user's name at write-time so the audit
--     stays meaningful even after the user is renamed or removed.
--   - old_value / new_value are JSON columns. We store the changed fields only (not the
--     entire row) to keep storage bounded; the calling service builds the JSON.
--   - ip_address is VARCHAR(45) so it accepts both IPv4 (max 15) and IPv6 (max 45).
--
-- INDEX STRATEGY:
--   - idx_audit_entity        → the dominant read path: "show me all audit rows for
--                                this order / this tp_account / etc." (timeline view).
--   - idx_audit_actor         → support query: "what did this user do recently?"
--   - idx_audit_impersonation → Admin Portal forensics: "what did this admin do?"
--
-- RETENTION:
--   No automatic retention enforced at the DB layer. A scheduled archival job (post-UAT)
--   moves rows older than 7 years to cold storage and deletes them — see
--   AuditLogRepository.deleteByCreatedAtLessThan.
--
-- ⚠️ NEVER edit this file once it has been applied. Create a new migration file with
--    the next sequence number for any change.
-- =============================================================================

CREATE TABLE audit_logs (
    -- Server-generated UUID. Stored as CHAR(36) for uniformity across the v5.0 schema.
    id                       CHAR(36)        NOT NULL,

    -- Database table name of the affected entity (e.g. 'orders', 'tp_accounts').
    -- We use table names rather than JPA class names so audit rows survive Java refactors.
    entity_type              VARCHAR(50)     NOT NULL,

    -- Primary key of the affected row, as the same CHAR(36) UUID format used everywhere
    -- else. Not constrained by FK — see header comment.
    entity_id                CHAR(36)        NOT NULL,

    -- What kind of mutation this row records. See AuditAction enum:
    --   CREATE | UPDATE | DELETE | STATE_CHANGE
    -- Stored as the enum's name() string.
    action                   VARCHAR(20)     NOT NULL,

    -- The users.id of the actor whose tokens were used to invoke the mutation.
    -- NULL for system-driven actions (scheduled jobs, etc.).
    -- For impersonation sessions this is the IMPERSONATED user, not the admin —
    -- see impersonated_by_user_id below.
    actor_user_id            CHAR(36)        NULL,

    -- Snapshot of the actor's display name AT THE TIME of the action. Survives renames /
    -- deletions of the users row.
    actor_name               VARCHAR(255)    NULL,

    -- For Admin-Portal impersonation sessions: the COGNILOGISTIC_ADMIN's users.id who
    -- triggered the session. NULL for non-impersonation activity.
    -- Indexed for "what did Admin X do?" forensic queries.
    impersonated_by_user_id  CHAR(36)        NULL,

    -- JSON snapshot of the row before the mutation. NULL on CREATE.
    -- Carries only fields that changed, not the entire row.
    -- PII columns (phone, name) are NOT redacted at write time — read-side redaction
    -- happens for non-privileged callers (post-UAT).
    old_value                JSON            NULL,

    -- JSON snapshot of the changed fields after the mutation. NULL on DELETE.
    new_value                JSON            NULL,

    -- Originating client IP. VARCHAR(45) to accept IPv4 (max 15) or IPv6 (max 45).
    -- NULL for system-internal events with no HTTP request context.
    ip_address               VARCHAR(45)     NULL,

    -- Server timestamp of insert. Set by AuditService.append(); the DB default is a
    -- safety net for any direct INSERTs.
    created_at               DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    -- Lookup an entity's audit timeline (most-used query).
    INDEX idx_audit_entity        (entity_type, entity_id),

    -- "What did user X do?" — support / impersonation review.
    INDEX idx_audit_actor         (actor_user_id),

    -- "What did this admin do across the platform?" — Admin Portal forensics.
    INDEX idx_audit_impersonation (impersonated_by_user_id)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Append-only cross-module audit trail. 7-year DPDP retention. v2.2.';
